repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--max-line-length=120"]

  - repo: local
    hooks:
      - id: update-index
        name: Auto Update _index.yaml for Phases
        entry: python3 tools/update_phase_index.py
        language: system
        files: ^cycle/
